# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c8a9c0027c70a990edb02bd50ce0139226dd359a88e36c02217fb7c6b5b0ca4d552aa59c242a6d145825feba2d69d5d8996ae1948fc4b4c7a2bc1f71b6f337

test:
  secret_key_base: 760fba019b20bc5eba26683af2cf6a12aa4db76a1ece96c9c659c0308747810099d4f171400be3741fb6321497db80bdc0c8aa1fcb2765ac08fbf513556d736b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
